### ISSUE TITLE
Optimize light client contract gas usage

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1006]
- [ ] optimize [_computeChallenges](https://github.com/EspressoSystems/espresso-sequencer/blob/708053ad2fef18ef3df449e87f7260a6420ac294/contracts/src/libraries/PlonkVerifier.sol#L207) function
- [ ] Have a look at Halo2 contract. [Sepolia tx](https://sepolia.etherscan.io/tx/0x5406db8685d617fd890eeac42670c5f5d2d47a13c9ecc899cef36b8119307712); [Sentio analysis](https://app.sentio.xyz/philippeespresso/espressolightclientcontract/transaction/11155111/0x5406db8685d617fd890eeac42670c5f5d2d47a13c9ecc899cef36b8119307712); [Rust Code](https://github.com/privacy-scaling-explorations/halo2/blob/main/halo2_backend/src/plonk/verifier.rs).
- [ ] - Do not load the verifying public key in the `verify` function. Instead hardcode its content everywhere needed (avoid passing it from functions to functions)

**Comment by alxiong** [comment]
as discussed, `forge`'s gas reporter only profile gas consumption at `CALL/CALLCODE/DELEGATECALL` level, thus their execution trace only show "external contract all" granular level. 
However, we want internal function call level profiling which is `JUMP`, and luckily both sentio and tenderly support this type of flamegraph at this level. (e.g. [from sentio](https://app.sentio.xyz/tx/1/0x4564f9720643fcf54732172d1f29b9a5f16991ca5ae171307181851c37511089))

So we should deploy our new PlonkVerifier to a testnet, and invoke functions on it, paste the tx hash into their explore to get the gas profile.

My friend at Sentio also told me that if we are happy with this, they can also open API for us, so we can send over our request and get the profiling back, and potentially integrate into our CI. That, of course, is future work.

**Comment by philippecamacho** [comment]
> as discussed, `forge`'s gas reporter only profile gas consumption at `CALL/CALLCODE/DELEGATECALL` level, thus their execution trace only show "external contract all" granular level. However, we want internal function call level profiling which is `JUMP`, and luckily both sentio and tenderly support this type of flamegraph at this level. (e.g. [from sentio](https://app.sentio.xyz/tx/1/0x4564f9720643fcf54732172d1f29b9a5f16991ca5ae171307181851c37511089))
> 
> So we should deploy our new PlonkVerifier to a testnet, and invoke functions on it, paste the tx hash into their explore to get the gas profile.
> 

Yes, SGTM.

**Comment by alxiong** [comment]
In comparison, PSE's halo2 plonk verifier ([code](https://github.com/privacy-scaling-explorations/halo2-solidity-verifier), example [`verify` tx](https://sepolia.etherscan.io/tx/0x5406db8685d617fd890eeac42670c5f5d2d47a13c9ecc899cef36b8119307712)) only takes 315k gas (less than half of ours) 

I will investigate deeper.

**Comment by philippecamacho** [comment]
Apparently there is so manual [approach](https://ethereum.stackexchange.com/questions/132323/transaction-gas-cost-in-foundry-forge-unit-tests) (analog to printf kind of debugging) using `gasleft()` solidity function.

I will try to bissect the code to identify the bottleneck.

**Comment by alxiong** [comment]
I think deploying it to testnet and use existing gas profiler on tenderly or sentio, is the easiest solution to begin with.

**Comment by philippecamacho** [comment]
Preliminary benchmark using sentio.

![screencapture-app-sentio-xyz-philippeespresso-espressolightclientcontract-transaction-11155111-0x5b8493a1782efd079a779fb6084877fea2a6c18a63df2a4f8d7ca60ac19c20c8-2024-02-19-17_50_57](https://github.com/EspressoSystems/espresso-sequencer/assets/7206973/62b5e93a-2fa4-4150-99be-9fd3fdd50216)

**Comment by alxiong** [comment]
can you paste the URL to this? @philippecamacho, need to zoom in. Thanks!

**Comment by philippecamacho** [comment]
> can you paste the URL to this? @philippecamacho, need to zoom in. Thanks!

Sure

https://app.sentio.xyz/philippeespresso/espressolightclientcontract/transaction/11155111/0x5b8493a1782efd079a779fb6084877fea2a6c18a63df2a4f8d7ca60ac19c20c8

You need to click on "Gas profiler"

**Comment by philippecamacho** [comment]
New profiling after optimizations:
https://app.sentio.xyz/philippeespresso/espressolightclientcontract/transaction/11155111/0x23991594bcfaeb90e86de85348ff89837cbdc68b6731ac8007b5750a568a871d

**Comment by philippecamacho** [comment]
Halo2 verifier profiling: https://app.sentio.xyz/philippeespresso/espressolightclientcontract/transaction/11155111/0x5406db8685d617fd890eeac42670c5f5d2d47a13c9ecc899cef36b8119307712
