### ISSUE TITLE
Equivalent of QueryableBlock::transaction_with_proof for namespaces

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/espresso-sequencer#1011]
Like #1010 except for namespaces. Next step after #1009 . As usual, this new method will not be added upstream to `QueryableBlock`. Instead just add it to the concrete `BlockPayload` struct in this repo. Suggested name: `namespace_with_proof`

**Comment by philippecamacho** [comment]
Wait until https://github.com/EspressoSystems/espresso-sequencer/issues/1011 is done.
