### ISSUE TITLE
Implement validated state

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/espresso-sequencer#1024]
Implement the `validate_block` function, performing all necessary merkle-tree validation (I believe we have some mock functions that currently do this) and move the block/fee merkle tree frontier out of the header.

**Comment by tbro** [comment]
This ticket is a little vague so I've tried to tie down some of the pieces. In  #1059 there are some first steps toward addressing this issue.

  * replace mock impl of `State` with logic that uses fee and block merkle trees for validation
  * add fee based validation to `fn _validate_proposal()`

**Comment by tbro** [comment]
closed in #1066
