### ISSUE TITLE
Add chaos logic to make commitment task randomly stop

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/espresso-sequencer#1026]
For chaos monkey testing to see how rollups react during random commit task outages

**Comment by nomaxg** [comment]
@jbearer @Ancient123 thoughts on whether this is better achieved by adding random delays to the commit task itself, or spinning down/up the task with some terraform logic?

**Comment by Ancient123** [comment]
Not terraform logic, but random delays and spinning up/down with AWS CLI tools

**Comment by nomaxg** [comment]
Sounds good, I can add some chaos monkey delay params to the task
