### ISSUE TITLE
Add builder info and fee amount to block header

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/espresso-sequencer#1044]
Add
* Builder `Address`
* Builder signature
* Builder fee amount
to `Header`

Note that signature is not part of the commitment scheme. It's not really conceptually part of the header at all, it's just there so that replicas receiving the header can validate the builder address. Thus it is possible to produce a signature by constructing a header with a dummy signature (or maybe have a different struct which is the header without the signature, which has the same commitment) signing it, and then setting the signature.

For now, until we have external builders, each sequencer node will also act as a builder, so we need to configure each sequencer with an Ethereum mnemonic so we can derive a private key and sign stuff.

Update validation to check the signature and subtract the fee from the builder's account.

**Comment by tbro** [comment]
Let me break this down into some tasks to make sure I understand:

In order to "configure each sequencer with an Ethereum mnemonic" we will need to:
  * add an clap param for the mnemonic to `options.rs`
  * add the related env var to `docker-compose.yaml`
  * derive key from mnemonic and retain it somewhere (alternatively derive it every time we use it)
  * derive address from key

In order to add builder signature we will:
  * sign header in `Header::genesis()`
  * sign header in `Header::new()`


Fee amount can just be a constant for now (every block costs 1 unit).

**Comment by jbearer** [comment]
> derive key from mnemonic and retain it somewhere

The place to retain this would be in the HotShot instance level state, which we can set up with data when we initialize hotshot and which then gets passed into each HotShot trait function. Unfortunately this doesn't exist quite yet, @shenkeyao is working on it. In the meantime you can just construct this on the fly like we do for the L1 client, or use a dummy key pair, or just wait to work on this issue until that is ready.

> sign header in Header::genesis()


I don't think the genesis block should have a signature, since we need all nodes to construct the exact same genesis. We are going to need some special casing for genesis anyways (see #1048 ) so maybe we can just make the builder address, signature, and fee amount optional, but enforce that they are present except in genesis.

**Comment by tbro** [comment]
> I don't think the genesis block should have a signature, since we need all nodes to construct the exact same genesis. We are going to need some special casing for genesis anyways (see #1048 ) so maybe we can just make the builder address, signature, and fee amount optional, but enforce that they are present except in genesis.

What if we had something like:

```
impl Header {
    fn sign(&self, builder_address: Address) -> SignedHeader {
        let signer = builder_address.get_key_mumbo_jumbo();
        let builder_signature = signer.sign_something_mumbo_jumbo(&self);
        SignedHeader {
            ..self,
            builder_signature
            
        }
    }
}
```
Then the signature could be enforced by the `SignedHeader` type. I guess one big downside would be having to update calles to use the new type. I don't have a clear idea of the effort involved in that but I can see how it could be prohibitive.

**Comment by jbearer** [comment]
I think the `SignedHeader` idea is nice but doesn't quite work with the current HotShot types, since replicas would receive the `Header` and not the `SignedHeader`, so they wouldn't be able to validate the signature
