### ISSUE TITLE
[cappuccino milestone] VID namespace proofs in live production

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/espresso-sequencer#1046]
Currently all the VID stuff is unused in `block2.rs`. Current namespace proofs are NMT-based in `block.rs`. We need to swap out NMT and use VID.

To this end we need to switch the namespace / tx proof query endpoints to use a VID struct instead of the NMT struct. In principle it should be just a matter of following the compiler.

@philippecamacho @akonring let's coordinate on who will take on this issue.

- [x] #1067 
- [x] #1080

**Comment by akonring** [comment]
Brief note after discussion on Zulip:
We might not want to have `Header`-related stuff in `block2.rs`.
Preliminary suggestion is to split `Header` into a separate file.
