### ISSUE TITLE
Proper `VidScheme` constructor shared with hotshot

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/espresso-sequencer#1047]
- Hotshot needs to initialize a `VidScheme` because hotshot is responsible for VID dispersal.
- The sequencer (this repo) needs it too because we're responsible for namespace/transaction proofs.
- Construction of this `VidScheme` should be done in one place and shared between hotshot and this repo. (Analogy: the `BlockPayload` trait is defined in hotshot and impl'ed in this repo.)
- Wherever it's constructed, it should be as opaque as possible. Example: a tiny "VID factory" module that exposes a function whose return type is `impl VidScheme`. (Actually `impl PayloadProver` but forget that.) This tiny module is the only place that "knows" the underlying impl for `VidScheme`; everything else talks to VID only via the `VidScheme` trait.

# Who hosts the factory?

VID scheme construction requires `num_storage_nodes`, `erasure_code_rate`, and `kzg_params`. Both hotshot and sequencer have (or can have) this data. Should the `VidScheme` be constructed in this repo or in hotshot?

## Reasons to do it here in the sequencer

- The sequencer is the application, hotshot is the library. As such, the params `num_storage_nodes`, etc are naturally set in the sequencer, not hotshot. (eg. source-of-truth for `num_storage_nodes` is the stake table, which is hosted in the sequencer.)

## Reasons to do it in hotshot

- Currently the sequencer needs `VidScheme` *only* for namespace/transaction proofs. It's conceivable that in the future a `VidScheme` instance is not needed to compute these proofs. By contrast, VID is core to hotshot and will always be there. If for some reason in the future the sequencer has no need for `VidScheme` at all then it's a hotshot-specific implementation detail that is now exposed to the sequencer, breaking modularity.

# Appendix: re-think VID scheme construction in jellyfish?

In order to make the ns/tx proofs we need, under the hood the ADVZ VID scheme in jellyfish needs:
1. `payload_chunk_size` (ie. polynomial degree), and
2. KZG params.

Is there a more ergonomic design for `PayloadProver` API in jellyfish? (eg. assoc function?) Or are we stuck constructing a fully-functional `VidScheme`?

**Comment by jbearer** [comment]
Gonna push back slightly:

> the params num_storage_nodes, etc are naturally set in the sequencer, not hotshot.

True, the sequencer maintains the stake table, which is the ultimate source of truth for number of storage nodes. But HotShot directs the sequencer in how to use the stake table: when to snapshot it, which snapshot to use at a given time. Plus, we don't always want the _current_ number of storage nodes. When generating namespace proofs e.g., we want the number of storage nodes which was used to disperse that block.

On top of this, parameters besides `num_storage_nodes, like the erasure coding rate, are really private to HotShot. The correct rate to use is a property of HotShot's failure threshold, and should not be up to the application to set.

How about we just add a function to HotShot `fn vid_scheme(num_storage_nodes: usize) -> VidScheme`? HotShot knows the number of storage nodes for the current block (from the `Membership` trait) and the application knows the number for a previous block based in the corresponding common data (which I am working on [adding to the query service](https://github.com/EspressoSystems/hotshot-query-service/issues/416) right now).

**Comment by ggutoski** [comment]
> But HotShot directs the sequencer in how to use the stake table: when to snapshot it, which snapshot to use at a given time.

Do hotshot and the sequencer both share a concept of block height? Because then `vid_scheme` might look like `fn vid_scheme(block_height: usize) -> VidScheme`. The idea is hotshot is probably already maintaining state such as: a mapping for each block height what is `num_storage_nodes`, etc? Presumably, if the sequencer is initializing different VID schemes for different block heights then `block_height` seems a natural index. This way the sequencer doesn't need to fetch `num_storage_nodes` (presumably itself a function of block height??) from hotshot only to serve it back as an arg to make a `VidScheme`.

**Comment by philippecamacho** [comment]
Do we need the block height or only the "epoch" height?

**Comment by jbearer** [comment]
Epoch height, but the problem is the same: the height is useless on its own, you have to use it to look up something else. This is unnecessary since ultimately we just need the number of nodes, and this is already stored on chain (via VID common)
