### ISSUE TITLE
FTLOG don't VID `disperse` in the namespace proof endpoint

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/espresso-sequencer#1093]
We should replace [VID `disperse`] with fetching the VID common data for this block (once the query service supports it) and using that to construct the VID scheme (once HotShot supports it), thus avoiding the need to disperse here

_Originally posted by @jbearer in https://github.com/EspressoSystems/espresso-sequencer/pull/1087#discussion_r1489576297_

**Comment by philippecamacho** [comment]
Related to #1047.
