### ISSUE TITLE
Nondeterministic test failure: test_namespace_query

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/espresso-sequencer#1102]
@nomaxg I'm getting nondeterministic test failure on 
```
cargo test --package sequencer --lib -- api::fs::generic_tests::test_namespace_query --nocapture
```

The failure occurs here https://github.com/EspressoSystems/espresso-sequencer/blob/fcb936e2ad25f79cf85adf92e4159f95101dbf00/sequencer/src/api.rs#L531-L535

Until now I've observed it only locally, typically after I've modified source files to trigger a rebuild. But now for the first time I saw it in CI: https://github.com/EspressoSystems/espresso-sequencer/actions/runs/7934874194/job/21666779930#step:8:248002

This test passes for me locally (most of the time). Perhaps it's a timing issue?

_Originally posted by @ggutoski in https://github.com/EspressoSystems/espresso-sequencer/issues/1087#issuecomment-1949244163_

**Comment by nomaxg** [comment]
I ran it last night and reproed the failure (unfortunately, forgot to capture the log, but there error was something like "FetchResource metric does not exist"). Running it in a loop locally, so far no errors. @jbearer any idea why that status endpoint may flunk out occasionally?

**Comment by nomaxg** [comment]
Looks good now
