### ISSUE TITLE
Remove calls to `just` in rust tests

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1177]
Not an issue with this PR but I'm not sure it's a great idea to call `just` from our rust tests. There doesn't seem to be much benefit from using `just` here it but we've created another dependency for a tool that isn't so commonplace and now needs to be installed to run `cargo test`. Any downside of using a bash script? What do others think about this?

_Originally posted by @sveitser in https://github.com/EspressoSystems/espresso-sequencer/pull/1139#discussion_r1505785291_

**Comment by sveitser** [comment]
I sort of agree that we shouldn't be calling external tools but I think the only way to avoid calling out to `forge` would be to re-implement our own deployment tooling in rust which is IMO not a great idea. We would never obtain similar functionality to forge and just create a lot more work for ourselves. I believe it's also possible to use forge as a library although supposedly not very convenient, so not sure it's worth going down that path.

We also want to keep tests isolated as much as possible so it often involves deploying a fresh blockchain and fresh contracts just to run one test. This makes debugging easier and allows us to do almost anything in tests. This was almost impossible before `anvil` because other ethereum development chains wouldn't start up fast enough. I wouldn't want to go back to the old way of doing it where you need to keep a long running blockchain service running alongside the tests. Therefore I'm not quite sure how task runners would help us here.

It's also nice to have some convenience just commands to deploy a contract to a dev chain which is what `dev-deploy` does.

I see just more of a convenience scripting tool so it's IMO a bit weird that one can break the rust tests by editing the justfile. Although I agree using bash scripts isn't better in this regard.

So maybe my opinion is that we should call forge directly from rust instead but keep whatever commands we think are useful to the justfile. We should also test important just commands on the CI... I really like just, there's nothing wrong with it :D

**Comment by tbro** [comment]
I understand the need to isolate tests, especially with the blockchain. I do feel that you might not *always* need *complete* isolation. In the specific case of the example, I really don't know. My feeling is that tests that require the same deployed contracts could share a setup, but again I'm unfamiliar with the specifics. And I take your point about slow startup. I agree that being able to setup/teardown the blockchain w/ anvil is fantastic. If you could do something similar to deploy contracts, I would vote for that. I also agree that we should **not** be developing our own deployment tooling.

**Comment by alxiong** [comment]
as pointed out in https://github.com/EspressoSystems/espresso-sequencer/pull/1307#discussion_r1559025335,
thanks to @jbearer's earlier work to enable deployment via rust, we can now safely remove the `forge script` in `just` command.

I'm working on this.
