### ISSUE TITLE
Gas Limit Adjustments

### ISSUE THREAD

**Issue by Symonpeetta** [EspressoSystems/espresso-sequencer#1182]
![image](https://github.com/EspressoSystems/espresso-sequencer/assets/65063958/24a034e1-8805-4dca-b91e-b9fa4d6e1416)
Upon deploying the contract on the testnet (devnet), I have observed that the gas fees associated with transactions on kyoto are significantly higher than anticipated. This poses a substantial barrier to testing and development efforts, as it may deter users from interacting with the project and hinder our ability to accurately assess its performance.

**Comment by sveitser** [comment]
The espresso sequencer has no control over the rollup gas fees. The altlayer team has adjusted the gas fees to 0.1 Gwei now. They also created a repository for issue with their testnet: https://github.com/alt-research/testnet-issues
