### ISSUE TITLE
VID bytes interpretation of duplicate namespace id

### ISSUE THREAD

**Issue by akonring** [EspressoSystems/espresso-sequencer#1258]
See discussion in [this doc](https://www.notion.so/Block-payload-format-with-namespace-transaction-tables-81425c5bd3ba495bafc3198ce287c487?d=017914ad21264d5e8b29bba51007a16c&pvs=4#523d02755fd940029e1512d952f28bc5).

### Considerations
While the simple rule of "ignore everything but the first entry with a specific ns_id" is simple, it might take some care to implement this into our namespace table code.

**Comment by ggutoski** [comment]
New PR #1499 implements this rule (ignore duplicate namespace IDs). Current plan is to use this rule pending merge of that PR.

However, we are currently discussing whether to disallow duplicate namespace IDs at the consensus level. See doc: [(1) Proposal: changes to namespace table](https://www.notion.so/espressosys/Proposal-changes-to-namespace-table-ca1dddb0edf549d286f368389efe182e)
