### ISSUE TITLE
Do not use `usize` in `add_new_entry_payload_len`

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1270]
https://github.com/EspressoSystems/espresso-sequencer/blob/708053ad2fef18ef3df449e87f7260a6420ac294/sequencer/src/block/tables.rs#L92

Code is conditionally wrong, depending on platform.

See https://espresso.zulipchat.com/#narrow/stream/330967-Sequencer/topic/Unintentional.20code.20auditing

**Comment by nyospe** [comment]
Specifically, for us, the size of a size will be 4 bytes on Wasm32 and maybe some RISC V appliances, and 8 bytes pretty much everywhere else.

**Comment by ggutoski** [comment]
Obsoleted by #1499
