### ISSUE TITLE
Builder API for users to submit txes and get builder address

### ISSUE THREAD

**Issue by ImJeremyHe** [EspressoSystems/espresso-sequencer#1289]
In our demo wallet, we assume that user will use a CLI argument to interact with the builder.

What we need:
- An endpoint to get the builder address and the wallet would build the guaranteed txs then
- An endpoint for users to submit tx to builder (stretch goal I believe)

**Comment by nyospe** [comment]
The second already exists. Not ideal naming, this can be updated, but the endpoint is `<builder-address>/submit/submit`
