### ISSUE TITLE
Don't turn on `testing` feature for non-test builds

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1491]
Need to at least remove `features = ["testing"]` from `sequencer = { path = "../sequencer", features = ["testing"] }` from the non-dev dependencies of builder. Then there are some compilation errors to fix because we have accidentally started to rely on the accidentally turned on "testing" feature.

Should be easier to fix when 
- https://github.com/EspressoSystems/espresso-sequencer/pull/1467

Is done because it will remove the call to `NodeState::mock()` which requires the "testing" feature.

**Comment by imabdulbasit** [comment]
```
error[E0599]: no function or associated item named `mock` found for struct `NodeState` in the current scope
   --> sequencer/src/block.rs:76:49
    |
76  |         Self::from_transactions([], &NodeState::mock()).unwrap()
    |                                                 ^^^^ function or associated item not found in `NodeState`
```

removing testing feature from builder results in this error.
https://github.com/EspressoSystems/espresso-sequencer/pull/1467

**Comment by imabdulbasit** [comment]
default implementation of NodeState requires the testing feature because if includes  MockStateCatchup, which is only available in the testing feature.
