### ISSUE TITLE
Document replicas verification on the namespace table and namespace table commitment definition

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1528]
In order to simplify the design of the circuit gadget checking the validity of namespace proofs and other conditions we will let the replicas perform the following verifications on the namespace table that is part of the block header:
* All namespace ids are unique
* The commitment to the namespace table is consistent with its definition.
* The commitment is a balanced merkle tree where each leaf contains a pair (namespace_id,offset) and leaves are sorted from left to right by namespace_id.

Document this design and identify the changes required in the current code of HotShot+Sequencer.

**Comment by ggutoski** [comment]
First draft: https://www.notion.so/espressosys/Proposal-changes-to-namespace-table-ca1dddb0edf549d286f368389efe182e

**Comment by philippecamacho** [comment]
@ggutoski Should we close this ticket?
