### ISSUE TITLE
Implement the new consensus rules in order to check the namespace table is well formed.

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1594]
Following the documentation related to https://github.com/EspressoSystems/espresso-sequencer/issues/1528.
Coordinate with the consensus team regarding breaking changes in the deployment pipeline.
See https://www.notion.so/espressosys/Proposal-consensus-changes-for-namespace-table-ca1dddb0edf549d286f368389efe182e#f95c6b2d3e684159bf0c47b0a11af280

**Comment by ggutoski** [comment]
D'oh! I made a dup issue #1605 . I'll use that one instead.
