### ISSUE TITLE
CommsEquivalence gadget

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1596]
- [ ]  Check out how Polygon transactions are represented and fed to their snark to evaluate how hard the proof of equivalence is to implement/compute.
    
       See https://github.com/0xPolygonZero/zk_evm?tab=readme-ov-file
    
    https://github.com/0xPolygonZero/zk_evm/blob/develop/docs/arithmetization/zkevm.pdf

**Comment by mrain** [comment]
I'm setting up the framework for "circuit" implementation here: https://github.com/EspressoSystems/zkrollup-integration/pull/2

**Comment by mrain** [comment]
Moved to https://github.com/EspressoSystems/zkrollup-integration/issues/8
