### ISSUE TITLE
Integrate postgres into dev-node binary

### ISSUE THREAD

**Issue by ImJeremyHe** [EspressoSystems/espresso-sequencer#1616]
Currently, we are required to run a standalone PostgreSQL instance when using our dev-node binary. To be more developer-friendly, we can provide a dev-node binary integrated with PostgreSQL.

If the relevant environment variables or options are not set, we can check if PostgreSQL has been installed locally:

- If yes, run PostgreSQL via the command line. This is the most common scenario because people tend to run the binary in a Docker container, and we can also build a Docker image for it.
- If no, display an error message indicating that PostgreSQL configuration should be set.

**Comment by tbro** [comment]
Why don't we just always run `TmpDb` as we [do in the tests](https://github.com/EspressoSystems/espresso-sequencer/blob/eec70e4f492a54a467e8dd95d038d97d4dbba7a9/sequencer/src/bin/espresso-dev-node.rs#L159)? This would work w/out configuration (I think).

**Comment by ImJeremyHe** [comment]
`TmpDb` starts a `postgres` by running the `docker` command. It would be a bit troublesome for users tending to run the dev node not through the `docker`. Though I am not sure if we can run a container in another container, this is also a mess when debugging.

**Comment by tbro** [comment]
> `TmpDb` starts a `postgres` by running the `docker` command. It would be a bit troublesome for users tending to run the dev node not through the `docker`. 

How so? It means that the dev-node would *just work*. User would not have to worry about postgresql. It would mean that docker would need to be available, but that is a *fairly* safe assumption these days. And, as above, they could provide configuration for their own postgresql in the case they couldn't/didn't want to use docker. 
 
> Though I am not sure if we can run a container in another container, this would be also a mess when debugging.

In the case dev-node is running inside docker, expected usage would be to provide your own postgresql. I think a very common usage would be w/ docker-compose, in which case user would include postgresq in docker-compose file and provide configuration to dev-node binary.

**Comment by ImJeremyHe** [comment]
> In the case dev-node is running inside docker, expected usage would be to provide your own postgresql. I think a very common usage would be w/ docker-compose, in which case user would include postgresq in docker-compose file and provide configuration to dev-node binary.

Running the `dev-node` in the docker compose file should be the most popular way for users. The point is that users should not pay any attention to the `postgres` because this is our internal issue and that's why the integration is needed. We may choose other ways to integrate the postgres later on, and the interfaces of `dev-node` should remain unchanged.
