### ISSUE TITLE
Light client contract state must contain a commitment to the block header

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1627]
In order to filter transactions per namespace, the light client contract state needs to contain a commitment to the block header, or more specifically the namespace table. [Currently](https://github.com/EspressoSystems/espresso-sequencer/blob/3b19fc2fbd21b1711922714ca3156bd59cec73e4/contracts/src/LightClient.sol#L105) the light client state only contains those fields:
 
 ```solidity
struct LightClientState {
        uint64 viewNum;
        uint64 blockHeight;
        BN254.ScalarField blockCommRoot;
        BN254.ScalarField feeLedgerComm;
        BN254.ScalarField stakeTableBlsKeyComm;
        BN254.ScalarField stakeTableSchnorrKeyComm;
        BN254.ScalarField stakeTableAmountComm;
        uint256 threshold;
    }
```

Discuss the issue with the team first.

**Comment by mrain** [comment]
Check Jeb's comment: this is not necessary.

**Comment by philippecamacho** [comment]
Jeb's comment copied here.

This is always going to be the case no matter what, because we don't update the light client contract for every block. Most of the time, the rollup is processing some earlier block and using the light client contract solely as the root for a merkle proof showing that that block was earlier sequenced.

Not having any information about the current block does indeed seem like an oversight, but a small one: it's only as if the light client state corresponds to one block earlier than it actually does. With a 4 hour posting interval, this one block offset doesn't matter much. We could add the hash of the current block if we really want to, I'm not sure there's much utility in going beyond that
