### ISSUE TITLE
Documentation for upgrades

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1686]
Add a markdown file in the `doc` folder that describes in some detail how upgrades work.

**Comment by tbro** [comment]
I think code should also be documented. [This](http://sequencer.docs.espressosys.com/sequencer/genesis/struct.Upgrade.html) isn't very useful to me. As a general process I would like to suggest we dial up considerably the documentation we add when modifying code. This includes both doc comments and regular comments. The markdown files in the `doc` folder can then lift and amplify information from these comments.
