### ISSUE TITLE
Change the rollup contract code so that it bypasses the snark proof verification.

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1700]
Follow these steps:
* Edit https://github.com/EspressoSystems/cdk-validium-contracts/blob/68f601a0de229047cbaf0ea55cfd262d73a76aae/contracts/verifiers/FflonkVerifier.sol#L162 and replace the code of the function with `return false;`
  * Rebuild the image
  * Upload the image somewhere (talk with Mat)
* Go to the [CDK Validium node repository](https://github.com/EspressoSystems/cdk-validium-node)
  *  Do `make run`
  *  Some errors should appear in the console
 *  Edit https://github.com/EspressoSystems/cdk-validium-contracts/blob/68f601a0de229047cbaf0ea55cfd262d73a76aae/contracts/verifiers/FflonkVerifier.sol#L162 and replace the code of the function with `return true;`
     * Rebuild the image
     * Upload the image somewhere (talk with Mat)
* Go to the [CDK Validium node repository](https://github.com/EspressoSystems/cdk-validium-node)
  *  Do `make run`
  *  No errors (at least related to snark proof verification) should appear in the console.

**Comment by ggutoski** [comment]
The `cdk-validium-contracts` repo seems intended only to build a docker image for the L2, not the L1:

- Chain ID for the deployed EVM chain is `1001` as per https://github.com/EspressoSystems/cdk-validium-contracts/blob/68f601a0de229047cbaf0ea55cfd262d73a76aae/deployment/deploy_parameters.json.example#L7, which is the "L2 Chain ID" listed in docs: https://github.com/EspressoSystems/cdk-validium-node?tab=readme-ov-file#usage

It's not yet clear to me how to tweak the docker image for the L1. Some confusing observations:

- In repo `cdk-validium-node` in file `test/docker-compose.yml` there is a docker container called `zkevm-mock-l1-network`. This name suggests that it's the L1 container. This container uses docker image `0xpolygon/cdk-validium-contracts:elderberry-fork.9-geth1.13.11`, which suggests that this image is built in repo `cdk-validium-contracts`. However, this suggestion conflicts with the above observation that repo `cdk-validium-contracts` seems intended to build a docker image for the L2, not the L1.
- The name of the docker image built in repo `cdk-validium-contracts` is `hermeznetwork/geth-cdk-validium-contracts` (see [docs](https://github.com/EspressoSystems/cdk-validium-contracts?tab=readme-ov-file#build-docker-image)), which does not match *any* of the docker image names appearing in repo `cdk-validium-node` in file `test/docker-compose.yml`.
  - The closest match is container `zkevm-v1tov2-l1-network`, which uses image `hermeznetwork/geth-zkevm-contracts:v2.1.1-lxly-updateV1ToV2-etrog-geth1.12.0`. I don't know the purpose of container `zkevm-v1tov2-l1-network`, but i's name suggests a relationship with the L1.
  - Thus, if the docker image built in repo `cdk-validium-contracts` is to be used anywhere in repo `cdk-validium-node` then one must manually rename one of the images listed in `test/docker-compose.yml`. This seems like a mistake: presumably, the image built in `cdk-validium-contracts` should be a drop-in replacement for *something* in `cdk-validium-node`. Either that, or there should be explicit instructions somewhere on how to use this image.

**Comment by ggutoski** [comment]
Posted new issue upstream: https://github.com/0xPolygon/cdk-validium-node/issues/150

**Comment by ggutoski** [comment]
Closing in favor of https://github.com/EspressoSystems/kurtosis-cdk/issues/1
