### ISSUE TITLE
update docs/upgrades.md 

### ISSUE THREAD

**Issue by imabdulbasit** [EspressoSystems/espresso-sequencer#1701]
There are now four additional parameters for time-based upgrade, so the docs needs to be updated.

**Comment by tbro** [comment]
I think some of the language in the docs can be clarified as well (either in the same PR or a different one). See [this zullip discussion for details](https://espresso.zulipchat.com/#narrow/stream/330967-Sequencer/topic/Upgrades/near/451505862). The gist of it is that the docs, while mentioning protocol upgrades, don't really help us understand what we mean by that, and instead focus on chain config migration. The outcome is the reader is led to believe that upgrades deal only with these migrations:

> an upgrade consists of two parts:

>A version bump
>A migration
>The version bump triggers a change to the protocol, which can include both a change in logic (e.g. if version >= NEXT_VERSION blocks will start executing) and a change in types. The migration has some effect on existing data (e.g. updating the chain config).

>So it would be good for our docs to make this distinction and say the only migration we currently support is to the chain config
