### ISSUE TITLE
Remove testing feature requirement for types crate 

### ISSUE THREAD

**Issue by imabdulbasit** [EspressoSystems/espresso-sequencer#1721]
Currently, when we use the types crate, we must include the testing feature because the default implementation of NodeState requires it.

 The default impl uses MockStateCatchup, which is only available in the testing feature.

**Comment by sveitser** [comment]
There's also still this issue: https://github.com/EspressoSystems/espresso-sequencer/issues/1491

@imabdulbasit maybe the issues can be merged into one?
