### ISSUE TITLE
Common Prefix audit

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1727]
Changes must be implemented in this branch https://github.com/EspressoSystems/espresso-sequencer/tree/commonprefix-patch.

- [x] #1816
- [x] #1763
- [x] #1632 
- [x] #1728
- [x] ~#1729~
- [x] #1730
- [x] #1731
- [x] #1732
- [x] #1733
- [x] #1734
- [x] #1735
- [x] #1736
- [x] #1737
- [x] #1738
- [x] #1739
- [x] #1740
- [x] #1741
- [x] #1756
- [ ] #1742
- [x] #1743
- [ ] #1744
- [x] #1745
- [x] #1746
- [x] #1747
- [ ] #1748
- [x] #1749
- [x] #1750
- [x] #1751
- [x] #1752
- [x] #1753
- [x] #1754
- [x] #1755
- [x] #1917

**Comment by alxiong** [comment]
As of 24 July, 2024: (among remaining tasks)

(reminded that all estimate are highly subjective, "High" effort usually means either changes required both from jellyfish and contract, or the amount of contract refactoring takes > 1 manday)

| Issue | Priority | Effort | Comments |
| --- | -- | -- | -- |
| M04, I01, I02,   | High | High | transcript refactoring |
| L05 | High | Mid-High | depends on L01 |
| I03 | High | - | PR in review |
| L01 | Mid | High | dynamic PI array |
| L02, L04, | Mid-Low | High | type safety (require lots of API changes) |
| L03 | Mid-Low | High | same round challenge gen |
| I07 | Mid-Low | Mid | centralize coset k constants |
| M03, L02, I18, I19  | Mid-Low | Low | canonical repr, input sanitization |
| I05, I09, I13, I14, I15, I16, | Mid | Low | simple perf improvement |
| I04, I06, I10, | Low | Low | still doable |
| I08, I11, I12, I17,   | Low | Low | lowest priority, only do them after rest is done |

**Comment by alxiong** [comment]
## Transcript Refactoring

Here is my tentative plan (in order): 
- I02: update contract to drop endianness
  - Jellyfish side already updated, working on this first would allow us to re-pin our jf dependency to the latest, and having all tests passing.
- M04: add `[x]_2` from SRS to transcript
  - this point is already part of the VK in jellyfish (inside the `VerifyingKey.open_key`), we just need to push it to transcript in rust code, then update the contract accordingly
- L03: allow multiple challenges per round
   - require changes from both Jellyfish and contract, but would be trivial in nature. `trait Transcript` would be updated.
- I01: efficiency of transcript
   - step 1: use typed transcript with concrete fields (this requires the most syntactic and API change in contract)
   - step 2: try using bytes array directly (and measure gas diff against step 1) 

My general rationale for this ordering is: let's update the logic first, and continuously making sure matching jellyfish prover and updated contract; leaving the efficiency improvement via major struct refactoring to the end, this could limit the moving parts for reviewers.

**Comment by philippecamacho** [comment]
@alxiong  I like the [plan](https://github.com/EspressoSystems/espresso-sequencer/issues/1727#issuecomment-2248368884). In particular sounds like a good idea to keep I01 for the end: IIRC hardcoding the hash of the verifying key in the transcript saves gas but not an enormous amount of it.

**Comment by alxiong** [comment]
Hey guys, I hope you're doing well.

We’re are still reviewing the recent fixes on PlonkVerifier.sol, and wanted to share some of the early findings with you. 
 
Here are the key points:

M03: The g1Deserialize function should revert when the infinity flag is set and other bits are non-zero. To prevent deserialization of invalid inputs.
M04: We’re unsure about how the G2 point is incorporated into the verifying key. When serializing them as separate G1 points, we noticed a discrepancy in the last byte of g2LSB (0x81 vs. 0x01).
L01: The input length check in _preparePcsInfo is unnecessary (because it is always false since we're using a fix sized array) and should be updated to if (verifyingKey.numInputs != 8) revert WrongPlonkVK();
L02: We suggest to add a comment at the start of the library regarding the canonical argument assumption.
I01: We recommend reusing the memory starting from the free memory pointer for each challenge generation, rather than appending, as this can prevent unnecessary memory expansion.

**Comment by philippecamacho** [comment]
> Feedback from Jakov:
> 
> Here are the key points:
> 
> * M03: The g1Deserialize function should revert when the infinity flag is set and other bits are non-zero. To prevent deserialization of invalid inputs.
> * M04: We’re unsure about how the G2 point is incorporated into the verifying key. When serializing them as separate G1 points, we noticed a discrepancy in the last byte of g2LSB (0x81 vs. 0x01).
> * L01: The input length check in _preparePcsInfo is unnecessary (because it is always false since we're using a fix sized array) and should be updated to if (verifyingKey.numInputs != 8) revert WrongPlonkVK();
> * L02: We suggest to add a comment at the start of the library regarding the canonical argument assumption.
> * I01: We recommend reusing the memory starting from the free memory pointer for each challenge generation, rather than appending, as this can prevent unnecessary memory expansion.
> 
> update:
> 
> * M03 and L02 addressed in [EspressoSystems/solidity-bn254@70c8225](https://github.com/EspressoSystems/solidity-bn254/commit/70c822572827cbbeff853c0d5e3213fe626587ec)

Created issue https://github.com/EspressoSystems/espresso-sequencer/issues/1917 to track progress on these observations.
