### ISSUE TITLE
M01: Use addmod for _computeLinPolyConstantTerm

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1728]
**Affected Code:**  PlonkVerifier.sol (lines 305,310,315,320)

**Summary:** The above-referenced lines use add instead of `addmod` for the parts of the calculations. Such calculations are implicitly performed modulo $2^{256}$, instead of modulo the order of the scalar field, which is
incorrect. In this particular instantiation, due to the size of the BN254 scalar field, the calculations will not overflow (i.e., for all previously reduced $a$ and $b$, $a+b < 2^{256}$), and the addition will take place over the integers. Still, this behavior is specific to BN254 and not documented. Using the same code on a different curve would produce erroneous results.

**Suggestion:** Switch to using addmod throughout, or alternatively add appropriate documentation to indicate a BN254-specific optimization.

**Status:** Pending

**Comment by alxiong** [comment]
Maybe "add appropriate documentation to indicate a BN254-specific optimization." is sufficient. 
TODO: add our original rationale later to explain why we only use add.

**Comment by philippecamacho** [comment]
Decision: let us be more consistent an use addmod everywhere.

**Comment by philippecamacho** [comment]
Closed in #1770.
