### ISSUE TITLE
M02: Start evaluatePiPoly and evaluateLagrangeOne enumeration from g1 instead of g0

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1729]
**Affected Code:** PolynomialEval.sol (lines 145,115)
**Summary:** Currently, evaluatePiPoly, and evaluateLagrangeOne start enumerating the group H from $g_0$, i.e., the coefficient for the public input is $g_0$ for the first, $g_1$ for the second, etc., instead of $g_1$ for the first, $g_2$ for the second, etc.
**Suggestion:** We suggest starting from $g_1$ for consistency with the paper, as this affects the alignment of the $L_1$ and $P I$ polynomials.
**Status:** Pending

**Comment by alxiong** [comment]
prev decision: require rewrite of arkwork’s own EvaluationDomain::elements() and etc. 
incur more refactoring and code changes that may introduce error 

Doesn't hurt security. Would argue to keep as it is but add documentation.

**Comment by philippecamacho** [comment]
Pyrros: apparently there is security issue, just flagged for consistency.
