### ISSUE TITLE
M04: Transcript does not include common preprocessed input, or any SRS elements

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1731]
**Affected Code:**
• Transcript.sol (line 81)
• IPlonkVerifier.sol (line 52)
**Summary:** The transcript currently does not include the entirety of the common preprocessed input (CPI) as specified in the Plonk paper. Rather, it includes the verification key in its place. This is partly acceptable as the elements of the verification key serve as commitments to the elements of the CPI. However, the struct `VerifyingKey` structure lacks any representative of the SRS, introducing an unexpected and undesired degree of freedom. In the paper, the $[x]_2$ is part of the verifier key, whereas in the code, it is represented as a “magic” value.
**Suggestion:** The $[x]_2$ value should be included in the struct `VerifyingKey` structure.
**Status:** Pending

**Comment by alxiong** [comment]
Since we hardcode in contract (magic value), attacker can't change them, thus can't equivocate on their value (similar effect on putting them in the transcript) 

But we agree maybe consistency is good, and will add these elements to the transcript (which incurs slightly more gas)

**Comment by philippecamacho** [comment]
Shresth: use immutable variables to handle testing in a convenient way. Immutable variables cannot be set in a library though.
