### ISSUE TITLE
L02: Ambiguity of canonical arguments assumption

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1734]
**Affected Code:** BN254.sol (lines 100,108,113)

**Summary:** As the field order is smaller than $2^{256}$, there are multiple valid representations of the same field element. Traditionally, the smallest non-negative integer is used as the canonical representation; however, other representations exist. Adding any integer multiple of the `R_MOD` to the canonical representation produces a value that behaves identically modulo `R_MOD`, but not in the integers or when treated as a byte string. It is unclear if the library consistently treats arguments as canonical across all functions. While this does not cause issues when used by the PLONK verifier contract, it could lead to potential problems in other contexts.

**Suggestion:** We recommend that all the functions (except `validateG1Point` and `validateScalarField`) that take a typed field element as an argument should assume that the representation is canonical and ensure that any field elements returned are also canonically represented. We have referenced above the functions that should be updated to reflect this assumption.

**Comment by alxiong** [comment]
the type alias was introduced in https://github.com/EspressoSystems/solidity-bn254/pull/7, and the plethora of unwrapping to do arithmetic and then warp it before returning does affect readability and increase code verbosity. 

I'm not too sure about the best practice here. I see verifier contract by Succinct, PSE etc all just using `uint256` directly (not typed) 

we should discuss with CommonPrefix on their suggestion more.

**Comment by philippecamacho** [comment]
Shresth: either use type safe operations or comment why the value is handled correctly.
