### ISSUE TITLE
L04: Type safety issues

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1736]
**Summary:** The code frequently wraps and unwraps library types to perform basic operations, which reduces readability and increases the risk of errors. There are inconsistencies in the types of arguments representing the same value across different functions. For example, in the `evaluateLagrangeOne` function, the variable ζ is represented by a `ScalarField` type, whereas in the `evalDataGen` and `evaluatePiPoly` functions, ζ is represented by a `uint256`.

**Suggestion:** We recommend using library types consistently throughout the codebase. Every typed variable should be assumed to be valid and canonical whereas every typecast (wrap/unwrap) operation should be validated or explicitly documented safe. We also recommend utilizing type-safe library functions to reduce the typecasting. Mind that there is a trade-off with the gas cost to perform an additional function call.

**Comment by alxiong** [comment]
the type alias was introduced in https://github.com/EspressoSystems/solidity-bn254/pull/7, and the plethora of unwrapping to do arithmetic and then warp it before returning does affect readability and increase code verbosity.

I'm not too sure about the best practice here. I see verifier contract by Succinct, PSE etc all just using uint256 directly (not typed)

we should discuss with CommonPrefix on their suggestion more.

**Comment by philippecamacho** [comment]
Estimation: HIGH

**Comment by philippecamacho** [comment]
With the new plonk verifier [PlonkVerifier2.sol](https://github.com/EspressoSystems/espresso-sequencer/blob/commonprefix-patch/contracts/src/libraries/PlonkVerifier2.sol), there are only a few calls to the wrap / unwrap functions. Closing ticket.
