### ISSUE TITLE
L05: Suboptimal verifier code due to missing MSM implementation

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1737]
**Affected Code:**
• PlonkVerifier.sol
• BN254.sol (line 173)

**Summary:** In the verifier code, particularly within the `_preparePolyCommitments` function, arrays of bases and scalars are allocated and passed between functions with the expectation of a valid Multi-Scalar Multiplication (MSM) implementation. However, the `multiScalarMul` function implementation only performs the naive iterative scalar multiplication and addition. This results in the following issues:

• The allocation (PlonkVerifier (lines L154,L482) ) and copying of arrays (PlonkVerifier.sol (line 488 - L493) ) result in unnecessary memory overhead.
• Introduce severe overhead in code complexity and gas cost for `_batchVerifyOpeningProofs` function.

**Suggestion:** We recommend refactoring the code to calculate the dot products and cumulative sums immediately instead of passing around the scalars and bases arrays and then applying the naive MSM algorithm.

**Comment by philippecamacho** [comment]
ESTIMATE: MEDIUM

**Comment by philippecamacho** [comment]
Depends on #1733.

**Comment by alxiong** [comment]
as I look into this issue today, I couldn't resist the urge of rewrite the majority of `_preparePcsInfo()` and `_verifyOpeningProof()` in a single assembly block. (since most of the logic is already in assembly, and the transition in and out of assembly and type conversion just looks ugly, and so inefficient)

please induge me, give me a day or two on this.

**Comment by alxiong** [comment]
@philippecamacho 
locally I have reduce the gas cost to **378442** 😊 after rewriting `prepare/verifyOpeningProof()`

so this is another 65k saving,
compared to the beginning of `commonprefix-patch`, we have reduced 118k gas on the PlonkVerifier.
