### ISSUE TITLE
I01: Inefficient memory allocation in transcript generation logic

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1738]
**Affected Code:**
• PlonkVerifier.sol (line 173)
• Transcript.sol (line 81)

**Summary:** The current implementation of the function `_computeChallenges` in PlonkVerifier.sol and `appendVkAndPubInput` in Transcript.sol inefficiently manages memory by repeatedly calling `abi.encodePacked` to concatenate elements to the transcript. Each call to `abi.encodePacked` results in a new memory allocation and copying of the existing transcript, leading to excessive gas consumption.

**Suggestion:** Create a struct containing all the fields that are appended to the transcript. Hash the parts of the struct using low-level memory access to generate the relevant challenges. To allow for tight packing of the transcript one can also use a bytes array instead of struct and low-level memory writes to populate the array.

**Comment by alxiong** [comment]
Completely agree!

Do they already have a PR on this? @philippecamacho

**Comment by philippecamacho** [comment]
ESTIMATION: HIGH

**Comment by alxiong** [comment]
I'm working on this, I'm gonna completely write the entire `_computeChallenges()` using assembly, this should improve gas usage noticeably. Will try to submit a PR tmr (can't finish today)
