### ISSUE TITLE
Increase of gas consumption in the light client contract

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#1816]
After this commit a93b964612c96158040a62ec855db4bfa3e104dc, the light client contract uses around 660k gas despite the plonk verifier being more gas efficient.

Understand the cause of this sudden increase.

See #1801 for more context.

**Comment by alxiong** [comment]
I looked into this today, now I know why:

<img width="935" alt="Screenshot 2024-08-12 at 4 42 27 PM" src="https://github.com/user-attachments/assets/2bfb7588-71ed-48ad-8b9f-f56c6eaffc84">


```solidity
// ======= before
        // check plonk proof
        verifyProof(newState, proof);

        // upon successful verification, update the latest finalized state
        states[finalizedState] = newState;
        emit NewState(newState.viewNum, newState.blockHeight, newState.blockCommRoot);

// ====== after or now:
        // check plonk proof
        verifyProof(newState, proof);

        // upon successful verification, update the latest finalized state
        states[finalizedState] = newState;

        //add the L1 Block to stateUpdateBlockNumbers for the new finalized state
        stateUpdateBlockNumbers.push(block.number);

        //add the blockheight and blockCommRoot to hotShotCommitments for the new finalized state
        hotShotCommitments.push(HotShotCommitment(newState.blockHeight, newState.blockCommRoot));

        emit NewState(newState.viewNum, newState.blockHeight, newState.blockCommRoot);
```

in short, this is expected. 
our saving in PlonkVerifier is reducing LightClient cost. (but admittedly the LC contract need serious optimization 🤦 )

**Comment by philippecamacho** [comment]
> our saving in PlonkVerifier is reducing LightClient cost. (but admittedly the LC contract need serious optimization 🤦 )

Awesome @alxiong ! Yes, I think @alysiahuggins has been working on some light client optimizations.
