### ISSUE TITLE
L3 support: deploy and run a prover on L2 locally for testing

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1820]
The user of the dev node should be able to optionally specify an L2 RPC URL (plus mnemonic and account index). The dev node should then also deploy the LightClient contract to the L2 and send proofs to it. The interaction with L1 should be unaffected, the Espresso sequencer still uses on the L1 and the L2 LC contract is only there for L3 rollups to use the L2 as parent chain.

**Comment by nomaxg** [comment]
@imabdulbasit @sveitser some progress here https://github.com/EspressoSystems/espresso-sequencer/tree/lc-multiple-providers

**Comment by imabdulbasit** [comment]
documentation needs to be updated
