### ISSUE TITLE
Reduce CI runtime

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1848]
Currently the "test" run takes almost 40 minutes. We should reduce this. Below are some ideas.

First collect information on how long all the required CI jobs take.

I think it would be good to split the up the test step into one step for building and one for running the tests:

https://github.com/EspressoSystems/espresso-sequencer/blob/f1270db9f82be0516790207044513893c47b4aef/.github/workflows/test.yml#L55-L57

This gives more visibility on which step takes how long.

Then it might make sense to get an idea on which tests are the slowest and see what we can do about it: for example, rewrite them, not run them on PRs by default. It would also be good if the CI made it easy to see which tests are slow. `nextest` would also take care of that.

If the time it takes to run tests is longer than the time it takes to build them we can consider splitting up the test job across github runners. `nextest` also makes this straightforward.

Another issue is that some tests are not well isolated. For this we can either fix those tests or use some combination of retries and timeouts to make the CI reliable enough. I think it should (falsely) fail in less than 1% of cases.

**Comment by tbro** [comment]
Some ideas.

  * We can quickly separate out `[[bin]]` tests. These are more or less like integration tests anyway. 
  * Properly organize integrations tests and run them separately (post-integration). We currently have most of these organized as if they were unit tests. To make them proper "integration" tests, we can simply create a `tests` folder under each crate and move them there. Alternatively we consider adding a `test` crate to the workspace.
  * [partitioning](https://github.com/nextest-rs/reuse-build-partition-example/blob/main/.github/workflows/ci.yml)

**Comment by Ayiga** [comment]
Posting this here for reference.  Running on `main` on my `macOS` here are a list of tests times obtained running the following command:

```sh
cargo nextest run --allfeatures --release --test-threads 1
```

```text
PASS [  10.526s] sequencer hotshot_commitment::test::test_idempotency
PASS [  14.575s] sequencer hotshot_commitment::test::test_sequencer_task
PASS [  14.962s] sequencer api::test::test_merklized_state_api
PASS [  21.118s] hotshot-state-prover service::test::test_read_contract_state
PASS [  21.408s] sequencer api::test::test_restart
PASS [  24.066s] sequencer api::test::test_chain_config_catchup
PASS [  32.438s] hotshot-state-prover service::test::test_submit_state_and_proof
PASS [  36.225s] sequencer test::test_header_invariants
PASS [  38.468s] sequencer api::test::test_catchup
PASS [  77.110s] espresso-types v0::impls::l1::test::test_wait_for_finalized_block
PASS [ 172.546s] sequencer::bin/espresso-dev-node tests::dev_node_test
```

These might be good tests to target to see if we can improve their speed in general.

**Comment by tbro** [comment]
> Posting this here for reference. Running on `main` on my `macOS` here are a list of tests times obtained running the following command:

I'm curious, do you not see any tests marked as `slow`? How does your output compare to:

https://github.com/EspressoSystems/espresso-sequencer/actions/runs/10385088247/job/28753461884

Node that you need to expand 2 test jobs in that link ^ to see all the output.

**Comment by Ayiga** [comment]
> > Posting this here for reference. Running on `main` on my `macOS` here are a list of tests times obtained running the following command:
> 
> I'm curious, do you not see any tests marked as `slow`? How does your output compare to:
> 
> https://github.com/EspressoSystems/espresso-sequencer/actions/runs/10385088247/job/28753461884
> 
> Note that you need to expand 2 test jobs in that link ^ to see all the output.

Oh yes!  I do see tests that take longer than a minute marked as slow.  In this case I just copied the `PASS` statements as it contained the total runtime.
