### ISSUE TITLE
Native demo test is not asserting that upgrades succeed

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1888]
We had an issue where the native-demo test was successful but the upgrade failed. The native demo should have stricter assertions to prevent it from passing if an upgrade fails.

**Comment by elliedavidson** [comment]
@sveitser Could we potentially prioritize this issue?  It's not part of marketplace work, but it will be nice to have so we can test just demo with the marketplace in CI.

**Comment by tbro** [comment]
will be handled in https://github.com/EspressoSystems/espresso-sequencer/issues/2053
