### ISSUE TITLE
[Docker] Non-root user

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/espresso-sequencer#2030]
Several operators have had issues overriding the default user in `docker-compose.yaml` when using a docker container. The main error is `message: "Permission denied"`, either from trying to save the config file or related FS data. Even when changing the storage path to somewhere accessible to that user via `ESPRESSO_SEQUENCER_STORAGE_PATH`, we are still seeing this issue

**Comment by sveitser** [comment]
- https://github.com/EspressoSystems/tide-disco/pull/238

**Comment by rob-maron** [comment]
We've since made the public directory a function of `/tmp` and a random number: https://github.com/EspressoSystems/tide-disco/pull/239/files
