### ISSUE TITLE
Cut releases for stable cloud deployment

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#522]
- [x] https://github.com/EspressoSystems/espresso-sequencer
- [x] https://github.com/EspressoSystems/espresso-polygon-zkevm-demo
- [x] https://github.com/EspressoSystems/zkevm-node
- [x] https://github.com/EspressoSystems/zkevm-contracts

**Comment by jbearer** [comment]
https://github.com/EspressoSystems/espresso-sequencer/tree/release-doppio-v1.0.0

**Comment by jbearer** [comment]
https://github.com/EspressoSystems/zkevm-node/tree/release-doppio-v1.0.0

**Comment by jbearer** [comment]
https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/tree/release-doppio-v1.0.0
