### ISSUE TITLE
Local multi rollup sequencer demo

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#602]
- The sequencer repo should have a docker compose file that includes an L1 devnet and the sequencer services (including the commitment task).
  + https://github.com/EspressoSystems/espresso-sequencer/pull/605
  + [x] #606 
- Each project should have a docker compose file to deploy it's own rollup node
  + [x] #607 
  + [x] #608 
- [x] #609

For the networking we can make the rollup compose envs join the network of the sequencer docker compose: https://docs.docker.com/compose/networking/#use-a-pre-existing-network

[zulip thread](https://espresso.zulipchat.com/#narrow/stream/330967-Sequencer/topic/OP.20.2B.20Polygon.20local.20demo)

**Comment by sveitser** [comment]
Let's call the network `espresso-sequencer`.

**Comment by nomaxg** [comment]
For the OP-stack, I think it might be easiest to modify the existing devnet-deploy script to optionally connect to another sequencer and geth instance. @sveitser what do you think?

**Comment by sveitser** [comment]
Yes. The makefile recipe `make devnet-up-espresso2` already only deploys a rollup to a running sequencer network. So hopefully all we need to do is make connect it to the pre-existing docker network of the sequencer.

**Comment by sveitser** [comment]
Also since anvil is much easier to setup and customize than geth maybe we can try first with using it as the L1 (like we currently do in the sequencer) and then switch to geth if things don't work with anvil.

**Comment by sveitser** [comment]
With the current setup the hotshot contract address will be `0x5fbdb2315678afecb367f032d93f642f64180aa3`.

**Comment by sveitser** [comment]
@nomaxg you could try to connect the OP node to the docker compose network in this PR: https://github.com/EspressoSystems/espresso-sequencer/pull/616

**Comment by sveitser** [comment]
Closing this as all subtasks completed.
