### ISSUE TITLE
Create new demo repo with submodules for sequencer and rollup projects

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#609]
The repo will make it easy to run the demo with the two rollups and any other integration we add in the future.

It will also serve as an authority of a working configuration for the full demo to avoid having to checkout specific commits of multiple repos to run the demo locally.

**Comment by nomaxg** [comment]
Minimal set of commands:

sequencer (start sequencer)
op (start op)
zkevm (start zkevm)
down (or clean, just stop and remove everything).

**Comment by sveitser** [comment]
Closing this as completed.

https://github.com/EspressoSystems/espresso-rollup-demo/blob/main/justfile
