### ISSUE TITLE
Problem: Deployment involves too many manual steps

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#649]
There are currently quite a few steps in deploying our cloud demo. Roughly:

1. Deploy hotshot contract -> deployment artifact
2. Start sequencer
3. Deploy L2 contracts -> deployment artifact
4. Start L2 services

In addition deployment outputs for the contract deployments need to be manually handled to make them inputs to subsequent tasks.

Step 1. and 3. require a funded wallet and infura and etherscan account.

I think we can do better feel free to leave ideas below. 

- A simple improvement would be to store the L2 contracts deployment artifacts inside the repo (similar to what `hardhat-deploy` and `forge script` are doing).

cc @Ancient123 @nomaxg @ImJeremyHe @jbearer

**Comment by Ancient123** [comment]
Also manual resets of databases, that is honestly the longest time-consuming task currently.

**Comment by alxiong** [comment]
> [!NOTE]
> This is dev notes for future reference 

While we can easily deploy contract like `contract_bindings::hot_shot::HotShot::deploy()`, for library-linking, there's no out-of-box support or tutorial in `ethers/foundry`, we have to hack around it. Notice that for contract that utilize a library, its rust bindings won't contain a `fn deploy()`.

credit to the previous attempts [here](https://github.com/worldcoin/signup-sequencer/blob/34daf4bcba2e75684ab29c8be94e48f1e708f3b2/tests/common/chain_mock.rs#L71), I wrote a similar deploy function below:

- first `cp contracts/out/LightClient.sol/LightClient.json artifacts/`
- add `foundry-compilers = { git = "https://github.com/foundry-rs/compilers" }` to `Cargo.toml`
- then define this
```rust
/// Deploy LightClient contracts, or panic if any intermediate steps fail
pub async fn deploy_contract(provider: Url, eth_signing_key: SigningKey) -> LightClient<L1Wallet> {
    #[derive(serde::Deserialize, serde::Serialize, Debug)]
    struct CompiledContract {
        bytecode: Bytecode,
    }

    let provider =
        Provider::<Http>::try_from(provider.to_string()).expect("error constructing provider");
    let signer = Wallet::from(eth_signing_key);
    let l1_wallet = Arc::new(L1Wallet::new(provider.clone(), signer));

    // first deploy PlonkVerifier contract
    let plonk_verifier = PlonkVerifier::deploy(l1_wallet.clone(), ())
        .expect("error constructing deployer instance")
        .send()
        .await
        .expect("error deploying PlonkVerifier contract");

    // second link with LightClient's bytecode artifacts
    let light_client_contract_json: CompiledContract = serde_json::from_reader(BufReader::new(
        File::open("./artifacts/LightClient.json")
            .expect("fail to find ./artifacts/LightClient.json"),
    ))
    .expect("fail to parse compiled contract");

    let mut light_client_bytecode_obj: BytecodeObject = light_client_contract_json.bytecode.object;
    light_client_bytecode_obj
        .link_fully_qualified("", plonk_verifier.address())
        .resolve()
        .expect("error linking PlonkVerifier lib");
    if light_client_bytecode_obj.is_unlinked() {
        panic!("failed to link PlonkVerifier library");
    }

    let light_client_factory = ContractFactory::new(
        LIGHTCLIENT_ABI.clone(),
        light_client_bytecode_obj
            .as_bytes()
            .expect("error parsing bytecode for linked LightClient contract"),
        l1_wallet,
    );
    // TODO: NOTE: for actual deployment, change the following to the intended genesis state!
    let genesis = ParsedLightClientState {
        view_num: 0,
        block_height: 0,
        block_comm_root: U256::from(42),
        fee_ledger_comm: U256::from(42),
        bls_key_comm: U256::from_str_radix(
            "0d168a6fe13a8b344caea06d1fd2a2f1e62eeb7b2b00c6284e094a819a1f1790",
            16,
        )
        .unwrap(),
        schnorr_key_comm: U256::from_str_radix(
            "2e4036835adc3ea606c3cc76870d7ed9fb0ae1ff435d96d480ce42420dfb8026",
            16,
        )
        .unwrap(),
        amount_comm: U256::from_str_radix(
            "03be29d3caf0c790070faa48051d86bfd6ec8c4ad4eef24af477741a180ee2ce",
            16,
        )
        .unwrap(),
        threshold: U256::from(36),
    };
    let genesis: contract_bindings::light_client::LightClientState = genesis.into();
    let light_client = ContractDeployer::new(
        light_client_factory
            .deploy((genesis, u32::MAX))
            .expect("error constructing deployer instance"),
    )
    .send()
    .await
    .expect("error deploying LightClient contract");

    light_client
}
```

Even with this, compiler will complain about `Address` in `ethers::core::types` is incompatible with `H160` in `foundry_compilers` (which supposed to supercede `ethers::solc`, a deprecated package)

Thus, we are currently stuck on this road.

With continual development on [`alloy-rs`](https://github.com/alloy-rs), a lot of these interop with `ethers` will be solved, and hopefully some built-in linking API will be provided.
For now, let's just use `forge script` for sanity.
