### ISSUE TITLE
Ensure codeowners files are up to date and working

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#656]
Should contain at least:

```
# These owners will be the default owners for everything in the repo. Unless a
# later match takes precedence, they will be requested for review when someone
# opens a pull request.

*       @nomaxg @philippecamacho @ImJeremyHe @sveitser @jbearer

#  Dependabot PRs
*.toml  @nomaxg @philippecamacho @ImJeremyHe @sveitser
*.lock  @nomaxg @philippecamacho @ImJeremyHe @sveitser
```

Some repos aren't rust repos but I think it's fine to use the same file anyway.

Repos / files:

- [x] https://github.com/EspressoSystems/espresso-sequencer/blob/main/CODEOWNERS
- [x] https://github.com/EspressoSystems/op-espresso-integration/blob/integration/CODEOWNERS
- [x] https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/blob/main/CODEOWNERS
- [x] https://github.com/EspressoSystems/sequencer-example-l2
- [x] https://github.com/EspressoSystems/op-geth
- [x] https://github.com/EspressoSystems/zkevm-node
- [x] https://github.com/EspressoSystems/espresso-rollup-demo

**Comment by ImJeremyHe** [comment]
These PRs are created to update/create CODEOWNERS files.
- [ ] https://github.com/EspressoSystems/espresso-sequencer/pull/695
- [ ] https://github.com/EspressoSystems/op-espresso-integration/pull/84
- [ ] https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/pull/248
- [ ] https://github.com/EspressoSystems/sequencer-example-l2/pull/3
- [ ] https://github.com/EspressoSystems/op-geth/pull/9
- [ ] https://github.com/EspressoSystems/zkevm-node/pull/83
- [ ] https://github.com/EspressoSystems/espresso-rollup-demo/pull/3
