### ISSUE TITLE
Add code coverage and run it on CI

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#683]
We can borrow from hotshot

- https://github.com/EspressoSystems/HotShot/blob/main/.github/workflows/coverage.yml

**Comment by tbro** [comment]
I've made a preliminary attempt in #1217 . Running locally llvm-cov is painfully slow... on the order of hours. And after the long wait something times out and you don't get any coverage. Maybe in the PR we can find the issue.
