### ISSUE TITLE
Understand hash oracle

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#685]
The deliverable here is a notion page describing in what way we will need to modify the hash oracle for the arbitrum integration.

https://docs.arbitrum.io/inside-arbitrum-nitro/#readpreimage-and-the-hash-oracle-trick

**Comment by sveitser** [comment]
@nomaxg @jbearer it currently looks like we won't be needing to modify the hash oracle so I think we can close this.

**Comment by jbearer** [comment]
Excellent!
