### ISSUE TITLE
Stake table contract implementation 

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/espresso-sequencer#737]
Follow up of #673

TODO:

- [x]  `register` function 
- [x]  `deposit` function
- [x] `requestExit` function
- [x] `withdrawFunds` function
- [x] Queue (registration and exit) logic (https://github.com/EspressoSystems/espresso-sequencer/pull/803)

**Comment by philippecamacho** [comment]
The leftover tasks/improvements have been migrated to #805.
