### ISSUE TITLE
Arbitrum integration: Ensure that the espresso block justification is serialized with batch data

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/espresso-sequencer#781]
Currently, we include the block justification in `L1IncomingMessageHeader`, but this never actually makes it to the L1. 

In https://github.com/EspressoSystems/nitro-espresso-integration/pull/14, we introduce a new message type, `L2MessageKind_EspressoTx`, so we theoretically should be able to append the justification to the end of the l2 message and parse it accordingly.

**Comment by nomaxg** [comment]
@ImJeremyHe what do you think of this approach?

**Comment by ImJeremyHe** [comment]
> Currently, we include the block justification in L1IncomingMessageHeader, but this never actually makes it to the L1.

`L1IncomingMessageHeader` is a [part of the message](https://github.com/EspressoSystems/nitro-espresso-integration/blob/5954ec37271a91bca8272a070b32783983c88fa7/execution/gethexec/executionengine.go#L186C18-L186C18) and now we get the `justification` [here](https://github.com/EspressoSystems/nitro-espresso-integration/blob/5954ec37271a91bca8272a070b32783983c88fa7/cmd/replay/main.go#L253). IIUC, the justification is serialized with batch data already.

**Comment by sveitser** [comment]
@ImJeremyHe @nomaxg we can close this right since

- https://github.com/EspressoSystems/nitro-espresso-integration/pull/20

has been merged?

**Comment by nomaxg** [comment]
yep 👍
