### ISSUE TITLE
Build fails => see screenshot attached

### ISSUE THREAD

**Issue by jonas089** [EspressoSystems/espresso-sequencer#845]
<img width="738" alt="Screenshot 2023-12-13 at 02 35 35" src="https://github.com/EspressoSystems/espresso-sequencer/assets/49498646/28d4136d-a776-4e6b-a8ab-a5585f83b8c9">

I'm struggling to setup a HotShot node. Ideally I'd like to run the espresso-sequencer without smart contracts and just test the submission & query functionality exposed by the API.  Is someone available to quickly walk me through these steps? 

Help would be much appreciated. Thanks in advance!

**Comment by jbearer** [comment]
@jonas089 I assume you figured this out? I believe you just needed to set `RUSTFLAGS` as we do in `flake.nix`

**Comment by jonas089** [comment]
yes, this could be added to the Readme to avoid confusion.

**Comment by jbearer** [comment]
It is noted [here](https://github.com/EspressoSystems/espresso-sequencer/blob/20231222/doc/ubuntu.md#run-the-rust-tests), linked from [here](https://github.com/EspressoSystems/espresso-sequencer/blob/20231222/README.md#development). Any suggestions on how we could make it more visible?

**Comment by jonas089** [comment]
I think it's alright but a small comment mentioning that the instructions in the readme only work inside the nix shell would have saved me some time. I acknowledge that this is not really a problem, just sharing my experience.
