### ISSUE TITLE
Sequencer key management

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/espresso-sequencer#934]
Derive sequencer keys from file instead of generating them from seed, integrating @dailinsubjam 's work.

**Comment by dailinsubjam** [comment]
This needs to wait for the PR to be closed: https://github.com/EspressoSystems/HotShot/pull/2247, which requires re-review from @rob-maron  & @shenkeyao. It would be great if you also take a look at the PR's "Comments requested" (especially the first two).

**Comment by dailinsubjam** [comment]
After discussion in today's meeting, we also need to get this done before sequencer integration: https://github.com/EspressoSystems/HotShot/issues/2416.

**Comment by nomaxg** [comment]
> After discussion in today's meeting, we also need to get this done before sequencer integration: [EspressoSystems/HotShot#2416](https://github.com/EspressoSystems/HotShot/issues/2416).

thank you @dailinsubjam !

**Comment by mrain** [comment]
After this issue, what's the ideal way to initialize a stake table as a non-participant of consensus?
Our light client prover service needs it.

**Comment by dailinsubjam** [comment]
> After this issue, what's the ideal way to get a stake table as a non-participant of consensus? Our light client prover service needs it.

By `getting a stake table`, do you mean light client prover need an endpoint to get the stake table? In Hotshot, stake value is now saved in `HotShotConfig::known_nodes_with_stake` which I guess you already learnt. From Consensus side, the stake value is still set to 1 as default. In short term it could also be imported from the config file [hotshot/crates/orchestrator/run-config.toml](https://github.com/EspressoSystems/HotShot/blob/main/crates/orchestrator/run-config.toml) right after `node_index` and `seed`. 
Would you guys love to set up a meeting to talk about this if there might be too many details included?

**Comment by sveitser** [comment]
@imabdulbasit I think there's nothing left to do here so closing it. Please re-open if necessary.
