### ISSUE TITLE
[light-client] prover service implementation

### ISSUE THREAD

**Issue by mrain** [EspressoSystems/espresso-sequencer#937]
Move `hotshot-state-prover` here, the light client related structs should be integrated in the sequencer crate. Others, circuit implementations, etc should be inside the prover service crate.

Implements a prover service that

- Read the stake table from contract.
- Read the current updated state from contract.
- Fetch the current light client state and the signatures from the relay server.
- Generate and submit the proof if there's an update.

**Comment by alxiong** [comment]
I can probably help on two sub-items: 1) using ethers-rs to read contract state; 2) serialize generated proofs and public inputs and send to contract.

**Comment by jbearer** [comment]
You can probably take the basic structure of `hotshot-commitment.rs` for this. We have made a number of improvements in how it handles synchronizing with the contract state, retry loop, etc that make it very reliable. Nothing special to do with the actual logic of the contract.
