### ISSUE TITLE
Smart contract specifications

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#945]
Only for

- Fee Token contract
- Light client contract

Output:

- readme
- graph
- workflow
- deployed addresses
- entrypoints

**Comment by alysiahuggins** [comment]
There are two PR's open for this ticket
- gitbook https://github.com/EspressoSystems/gitbook/pull/16
- code (comments) https://github.com/EspressoSystems/espresso-sequencer/pull/1078
