### ISSUE TITLE
Benchmark light client contract gas usage

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/espresso-sequencer#947]
Foundry/Forge can produce [gas reports](https://book.getfoundry.sh/forge/gas-reports), does this need to be added to a CI/CD pipeline?

There’s another feature called [gas snapshots](https://book.getfoundry.sh/forge/gas-snapshots) which can be used to see how much gas your tests consumed and can be used to compare gas before and after optimizations. It creates a file called, .gas-snapshot with the gas consumption info for running the test. With the gas snapshots, You can also select a file for comparing your current run to a previous one.

**Comment by alxiong** [comment]
A local run shows:

```
$ forge test --mc LightClient_newFinalizedState_Test --mt testFuzz_ConsecutiveUpdate --gas-report 
| contracts/test/mocks/LightClientTest.sol:LightClientTest contract |                 |        |        |        |         |
|-------------------------------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                                                   | Deployment Size |        |        |        |         |
| 1675066                                                           | 7646            |        |        |        |         |
| Function Name                                                     | min             | avg    | median | max    | # calls |
| computeStakeTableComm                                             | 1098            | 1098   | 1098   | 1098   | 6       |
| currentEpoch                                                      | 337             | 337    | 337    | 337    | 4       |
| finalizedState                                                    | 1196            | 1196   | 1196   | 1196   | 4       |
| frozenStakeTableCommitment                                        | 340             | 340    | 340    | 340    | 4       |
| frozenThreshold                                                   | 383             | 383    | 383    | 383    | 4       |
| newFinalizedState                                                 | 825916          | 838290 | 827721 | 871804 | 4       |
| votingStakeTableCommitment                                        | 317             | 317    | 317    | 317    | 4       |
| votingThreshold                                                   | 406             | 406    | 406    | 406    | 4       |
```

IMO, we only care about gas cost of `newFinalizedState` at this stage, the rest are mostly noise.
Since the main cost is plonk verification , we should also gas profile our PlonkVerifier.t.sol, unfortunately the gas report breakdown only works for contract, not library, so we simply run the test:

```
$ forge test --mc PlonkVerifier_verify_Test --mt test_verify_succeeds 
[PASS] test_verify_succeeds() (gas: 781526)
```

**Comment by philippecamacho** [comment]
> I think we can simply log the output of forge test --gas-report in CI,
> I also tried gas snapshot which is not too different from gas report, the gas snapshot --dff could be handy, but given that we are only targetting a single function to optimize, setting up an infra or auto-logging seems an overkill atm, especially we don't touch verifier code often. (open to ideas)
> 
> one thing I wish we have but forge doesn't seem to support is proper profiling (i.e. break down of which sub-procedure call of my PlonkVerifier.verify() took how much/percentage of gas consumption.
> ^^ I'll explore more on this. also, if we could have this profiling working, then I'd like to log this in CI as well.
> 
> Another fancy possible future work, is to setup a Github Bot, like [codecov.io](https://about.codecov.io/), triggered by some events or a comment in PR comment, it will run a gas diff report on the optimization status.
> again I think this is overkill for now.

I agree that we should keep it simple for now. Running `forge test --gas-report` in CI is enough at this stage.

Let us keep profiling for #1006.
