### ISSUE TITLE
Validate existing header fields once HotShot supports validated state

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/espresso-sequencer#968]
* `height` increases by 1
* `timestamp` is within some delta of the current time and not decreasing
* L1 head is within some delta of the current L1 head and not decreasing
* L1 finalized is accurate, within some delta of the current L1 head, not in the future, and not decreasing

**Comment by tbro** [comment]
from [zulip](https://espresso.zulipchat.com/#narrow/stream/330967-Sequencer/topic/Updates/near/450447114): 

> I think we are missing these checks:
> - [ ] timestamp is within some delta of the current time
> - [ ] L1 head is within some delta of the current L1 head
> - [ ] L1 finalized is accurate, within some delta of the current L1 head, not in the future

> I think to properly enforce these we should add some parameters to the chain config:
>   * max_time_drift
>   * max_l1_head_drift
>   * max_l1_finalized_drift

> Adding these would be a breaking change, so let's circle back to this after the versioning PR is merged, and we can incorporate these checks into 0.3 along with the marketplace
